// ALGORITMA PSEDUOCODE
/**
 * STUDY CASE 1
 * 
 * TENTUKAN ALGORTIMA DAN PSEUDUCODE UNTUK MENGHITUNG KELILING PERSEGI PANJANG
 * 
 * SDTUDY CASE 2
 * 
 * TENTUKAN ALGORITMA DAN PSEUDUCODE UNTUK MENGHITUNG LUAS PERMUKAAN TABUNG
 * 
 * STUDY CASE 3
 * 
 * TENTUKAN ALGORITMA DAN PSEUDUCODE VOLUME 1/4 VOLUME BOLA
 */

//STUDY CASE  1

let panjang = 10;
let lebar = 8;

let keliling = 2 * (panjang + lebar);
console.log("Keliling persegi panjang adalah : " +keliling);